# -*- coding: utf-8 -*-
"""Taller problemas 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abEcem0gZUl9iTkVUKWTpqkakqDznIJI
"""

import sympy
from sympy import *

x, y = symbols('x y')
def vector_coefs_simple(p,g):
    P= Poly(p, x)
    G= Poly(g, y)
    N = 2
    u= Matrix([P.coeff_monomial(x**i) for i in range(N+1)])
    v= Matrix([[G.coeff_monomial(y**i) for i in range(N+1)]])
    return u*v

x_0, x_1, x_2, y_0, y_1, y_2 = symbols('x_0 x_1 x_2 y_0 y_1 y_2')
p= x_0+x_1*x+x_2*x**2
g= y_0+y_1*y+y_2*y**2
vector_coefs_simple(p,g)

p= x**2+x+1
g= y+1
prod_pol= expand(p*g)
prod_pol

def P_n(p):
  P = []
  for i in range(3):
    Pn = legendre(i,x)
    A = Rational(2*i+1, 2)
    I = integrate(p * Pn, (x, -1, 1))
    P.append(A * I*Pn)
  return P

p = x**2 + x + 3
P_n(p)

x, y = symbols('x y')
def vector_coefs_simple(p,g):
    P= Poly(p, x)
    G= Poly(g, y)
    N = 2
    u= Matrix([P.coeff_monomial(x**i) for i in range(N+1)])
    v= Matrix([[G.coeff_monomial(y**i) for i in range(N+1)]])
    return u*v

def C_n(p, g):
  M = []
  H = []
  for i in range(3):
    Pnx = legendre(i,x)
    Pny = legendre(i,y)
    A = Rational(2*i+1, 2)
    Intx = integrate(p * Pnx, (x, -1, 1))
    Inty= integrate(g * Pny, (y, -1, 1))
    M.append(A * Intx)
    H.append(A * Inty)
  return Matrix(M)*Matrix([H])

p= x_0+x_1*x+x_2*x**2
g= y_0+y_1*y+y_2*y**2
a=x**2 + x + 3
b=y+1
C_n(a,b)